server:
  port: 3000
application:
  domain: "flight-cl.ub"
  name: "Flight Club"
  logo: "Flight_Logo.png"
  numberOfRandomFakeUsers: 0
  showChallengeSolvedNotifications: true
  showCtfFlagsInNotifications: true
  showGitHubRibbon: false
  showChallengeHints: false
  theme: "readable" # Options: cerulean  cosmo  cyborg  darkly  flatly lumen  paper  readable  sandstone  simplex  slate  spacelab  superhero  united  yeti
  twitterUrl: "https://twitter.com/flightclub"
  facebookUrl: "https://www.facebook.com/Flight-Club-194401846124/"
  recyclePage:
    topProductImage: "box_jet.jpg"
    bottomProductImage: "box2.jpg"
products:
  - name: "Kid on an Old-School Plane"
    price: 1.99
    description: "The all-time classic."
    image: "apple_juice.jpg"
  - name: 'Plane in the Clouds'
    description: 'How peaceful'
    price: 2.99
    image: 'plane1.jpg'
  - name: 'Blue Plane'
    description: 'Now with even more exotic clouds'
    price: 8.99
    image: 'plane2.gif'
  - name: 'Happy Plane!'
    description: 'Who doesn't like their animated friends?'
    price: 4.99
    image: 'plane3.png'
  - name: 'Old-School Plane'
    description: 'Bring the Wright Brothers back'
    price: 2.99
    image: 'plane4.png'
  - name: 'New Plane'
    description: 'Moving to the future.'
    price: 1.99
    image: 'plane5.png'
  - name: 'Pilot Tee'
    description: 'Real fans wear it 24/7!'
    price: 22.49
    image: 'shirt1.jpg'
  - name: 'Branded Tee'
    description: 'For serious fans only!'
    price: 22.49
    image: 'shirt2.jpg'
  - name: 'Tools'
    description: 'Useful'
    price: 0.01
    image: 'tools.jpeg'
    useForProductTamperingChallenge: true
  - name: 'Christmas Super-Surprise-Box (2014 Edition)'
    description: 'Contains a random selection for an unbeatable price!'
    price: 29.99
    image: 'box.jpg'
    useForChristmasSpecialChallenge: true
  - name: 'Blue Sticker (2015/2016 design)'
    description: 'It's a blue plane sticker! <em>Out of stock!</em>'
    price: 999.99
    image: 'sticker1.png'
    deletedDate: '2017-04-28'
  - name: 'Simple Sticker'
    description: 'You want to put <a href="https://www.stickermule.com/de/user/1070702817/Sticker" target="_blank">one of these beauties</a> on your laptop. You definitely want that. Trust me.'
    price: 2.99
    image: 'sticker2.jpg'
  - name: 'Paper Plane Sticker'
    description: 'This is a mandatory laptop decal.'
    price: 2.99
    image: 'sticker4.png'
  - name: 'Plane Mug'
    description: 'Your colleagues will envy you!'
    price: 21.99
    image: 'mug1.jpg'
  - name: 'Pilot Mug'
    description: 'Born to fly.'
    price: 49.99
    image: 'mug2.jpg'
  - name: 'An Award'
    description: 'Made from metal'
    price: 1.99
    image: 'award.jpg'
  - name: 'Blue Plane (3D-printed)'
    description: 'This rare item was designed and handcrafted in Sweden. This is why it is so incredibly expensive despite its complete lack of purpose.'
    price: 99.99
    image: '3dprint.jpg' # Exif metadata contains "OpenSCAD" as subtle hint...
    fileForRetrieveBlueprintChallenge: 'JuiceShop.stl' # ...to blueprint file type
