server:
  port: 3000
application:
  domain: kiwaworksh.op
  name: 'Kiwa Workshop'
  logo: kiwa_logo.png
  favicon: favicon_js.ico
  theme: bluegrey-lightgreen # Options: bluegrey-lightgreen blue-lightblue deeppurple-amber indigo-pink pink-bluegrey purple-green deeporange-indigo
  showChallengeSolvedNotifications: true
  showChallengeHints: true
  showVersionNumber: false
  showHackingInstructor: true
  showGitHubLinks: true
  numberOfRandomFakeUsers: 0
  twitterUrl: 'https://twitter.com/owasp_juiceshop'
  facebookUrl: 'https://www.facebook.com/owasp.juiceshop'
  slackUrl: 'http://owaspslack.com'
  redditUrl: 'https://www.reddit.com/r/owasp_juiceshop'
  pressKitUrl: 'https://github.com/OWASP/owasp-swag/tree/master/projects/juice-shop'
  planetOverlayMap: orangemap2k.jpg
  planetName: Orangeuze
  deluxePage:
    deluxeDeliveryImage: delivery_kiwa.png
  recyclePage:
    topProductImage: undefined_kiwa.png
    bottomProductImage: undefined_kiwa.png
  altcoinName: KiwaKoin
  welcomeBanner:
    showOnFirstStart: true
    title: 'Welcome to OWASP Kiwa Workshop!'
    message: "<p>Being a web application with a vast number of intended security vulnerabilities, the <strong>Kiwa Workshop</strong> is supposed to be the opposite of a best practice or template application for web developers: It is an awareness, training, demonstration and exercise tool for security risks in modern web applications. The <strong>OWASP Juice Shop</strong>, which the Kiwa Workshop is based on, is an open-source project hosted by the non-profit <a href='https://owasp.org' target='_blank'>Open Web Application Security Project (OWASP)</a> and is developed and maintained by volunteers. Check out the link below for more information and documentation on the project.</p><h1><a href='http://owasp-juice.shop' target='_blank'>http://owasp-juice.shop</a></h1>"
  cookieConsent:
    backgroundColor: '#546e7a'
    textColor: '#ffffff'
    buttonColor: '#558b2f'
    buttonTextColor: '#ffffff'
    message: 'This website uses a myriad of 3rd-party cookies, abuses cookies and cookiewalls for our own gain and to ensure you get the best tracking experience.'
    dismissText: 'Never Mind'
    linkText: 'lmgtfy'
    linkUrl: 'https://www.lmgtfy.com'
  privacyContactEmail: donotreply@kiwa-work.shop
  securityTxt:
    contact: 'mailto:donotreply@kiwa-work.shop'
    encryption: 'https://keybase.io/bkimminich/pgp_keys.asc?fingerprint=19c01cb7157e4645e9e2c863062a85a8cbfbdcda'
    acknowledgements: '/#/score-board'
  promotion:
    video: JuiceShopJingle.mp4
    subtitles: JuiceShopJingle.vtt
challenges:
  safetyOverride: false
  overwriteUrlForProductTamperingChallenge: 'https://owasp.slack.com'
products:
  -
    name: 'Kiwa Beaver'
    price: 18.99
    deluxePrice: 20.99
    description: 'The Original'
    image: beaver.jpg
    reviews: # Options 'author': admin, jim, bender, ciso, support, morty, mc.safesearch
      - { text: 'One of my favorites!', author: admin }
  -
    name: 'Bag Jute'
    description: 'An environmental friendly bag'
    price: 3
    deluxePrice: 6.00
    image: blauwetas.jpg
  -
    name: 'Cotton Shopper'
    description: 'Cotton material'
    price: 1.63
    image: cottontas.jpg
    reviews:
      - { text: 'I bought it, would buy again. 5/7', author: admin }
  -
    name: 'Special Package 1'
    description: 'This Very Splendid Package includes a ladies Kiwa navy t-shirt, a cap, and a coffee mug in a Kiwa Jute bag.'
    price: 37
    image: undefined_kiwa.png
  -
    name: 'Special Package 2'
    description: 'This Very Splendid Package includes a unisex navy polo, a cap, and a coffee mug in a Kiwa Jute bag.'
    price: 37
    image: undefined_kiwa.png
  -
    name: 'Special Package 3'
    description: 'The Most Splendid Package includes a Kiwa Champion sweatshirt in a drawstring tote, a Beaverskin notebook, and a Kiwa Commuter 2.0 Laptop Bag.'
    price: 300.89
    image: undefined_kiwa.png
    reviews:
      - { text: 'Fry liked it too.', author: bender }
  -
    name: 'Kiwa Unisex polo, navy'
    price: 13.51
    image: polonavy.jpg
  -
    name: 'Kiwa baby T-shirt Pink'
    price: 13.51
    image: shirtroze.jpg
  -
    name: 'Kiwa baby T-shirt Blue'
    price: 13.51
    image: shirtblauw.jpg
  -
    name: 'Kiwa cap'
    description: 'including embroidery of the Kiwa logo on the back'
    price: 17.75
    image: cap.jpg
  -
    name: 'Kiwa Cycling Tight Long'
    price: 35.5
    image: cyclingtightlong.jpg
    reviews:
      - { text: 'One of my favorites.', author: jim }
  -
    name: 'Kiwa Cycling Tight Short'
    description: 'What more to say'
    price: 25.5
    image: cyclingtightshort.jpg
  -
    name: 'Join the Pipe waterbottle'
    description: 'Transparent waterbottle with Kiwa logo printed in two colours'
    price: 8.81
    image: jointhepipe.jpg
  -
    name: 'Kiwa USB stick'
    description: '4gb'
    price: 10.11
    image: usb.jpg
  -
    name: 'Kiwa Helmet USB stick'
    description: '4gb'
    price: 16.11
    image: helmetusb.jpg
  -
    name: 'Kiwa Powerbank'
    price: 15.32
    image: powerbank.jpg
    reviews:
      - { text: 'Fry liked it too.', author: bender }
  -
    name: 'Kiwa Lanyard'
    price: 2.33
    image: lanyard.jpg
  -
    name: 'Kiwa Bic pen'
    price: 1.65
    image: bic.jpg
  -
    name: 'Kiwa pens, 50 pack'
    price: 50.00
    image: pens.jpg
  -
    name: 'Kiwa Tie blue'
    price: 7
    image: tieblue.jpg
  -
    name: 'Kiwa Tie green'
    price: 7
    image: tiegreen.jpg	
  -
    name: 'Kiwa Tie purple'
    price: 7
    image: tiepurple.jpg	
  -
    name: 'Kiwa Tie red'
    price: 7
    image: tiered.jpg	
  -
    name: 'Kiwa Flag Large'
    price: 14.63
    image: flaglarge.jpg
  -
    name: 'Kiwa Flag medium'
    price: 10.63
    image: flagmedium.jpg
  -
    name: 'Kiwa Flag small'
    price: 8.63
    image: flagsmall.jpg
  -
    name: 'OWASP SSL Advanced Forensic Tool (O-Saft)'
    description: 'O-Saft is an easy to use tool to show information about SSL certificate and tests the SSL connection according given list of ciphers and various SSL configurations.'
    price: 0.01
    image: undefined_kiwa.png
    urlForProductTamperingChallenge: 'https://www.owasp.org/index.php/O-Saft'
  -
    name: 'Christmas Super-Surprise-Box (2018 Edition)'
    description: 'Contains a random selection of 10 bottles (each 500ml) of our tastiest juices and an extra fan shirt for an unbeatable price!'
    price: 29.99
    image: undefined_kiwa.png
    useForChristmasSpecialChallenge: true
  -
    name: 'OWASP Juice Shop Sticker (2015/2016 design)'
    description: 'Die-cut sticker with the official 2015/2016 logo. By now this is a rare collectors item. <em>Out of stock!</em>'
    price: 999.99
    image: sticker.png
    deletedDate: '2017-04-28'
  -
    name: 'Kiwa tape rolls (16pcs)'
    description: 'Get one of these <a href="https://www.stickeryou.com/products/owasp-juice-shop/794" target="_blank">temporary tattoos</a> to proudly wear the OWASP Juice Shop or CTF Extension logo on your skin! If you tweet a photo of yourself with the tattoo, you get a couple of our stickers for free! Please mention <a href="https://twitter.com/owasp_juiceshop" target="_blank"><code>@owasp_juiceshop</code></a> in your tweet!'
    price: 14.99
    image: taperolls.jpg
    reviews:
      - { text: 'I straight-up gots nuff props fo''these rolls!', author: mc.safesearch }
  -
    name: 'Surfing Beaver'
    description: 'Kiwa Surfin' Beaver. Your colleagues will envy you!'
    price: 21.99
    image: surfinbeaver.jpg
  -
    name: 'Kiwa Storm Umbrella'
    description: 'Mary Poppins-style apparel. But in black. And with the Kiwa logo.'
    price: 49.99
    image: stormumbrella.jpg
  -
    name: 'Kiwa table flag'
    description: 'You're getting flagged'
    price: 2.99
    image: tableflag.jpg
  -
    name: 'Kiwa clip-on'
    description: 'The ultimate decal for every tactical bag or backpack!'
    price: 2.92
    quantity: 5
    image: clip.jpg
    reviews:
      - { text: 'This thang would look phat on Bobby''s jacked fur coat!', author: mc.safesearch }
      - { text: 'Looks so much better on my uniform than the boring Starfleet symbol.', author: jim }
  -
    name: 'Green Smoothie'
    description: 'Looks poisonous but is actually very good for your health! Made from green cabbage, spinach, kiwi and grass.'
    price: 1.99
    image: green_smoothie.jpg
    reviews:
      - { text: 'Fresh out of a replicator.', author: jim }
  -
    name: 'OWASP Juice Shop Logo (3D-printed)'
    description: 'This rare item was designed and handcrafted in Sweden. This is why it is so incredibly expensive despite its complete lack of purpose.'
    price: 99.99
    image: 3d_keychain.jpg # Exif metadata contains "OpenSCAD" as subtle hint...
    fileForRetrieveBlueprintChallenge: JuiceShop.stl # ...to blueprint file type
  -
    name: 'Workshop Artwork'
    description: 'Unique masterpiece painted with different kinds of paint on 90g/m² lined paper.'
    price: 278.74
    quantity: 1
    image: undefined_kiwa.png
  -
    name: 'Kiwa Keychain'
    description: 'I did all of this work and then i got only this Kiwa keychain.'
    price: 3.74
    quantity: 6
    image: beavertail.jpg
  -
    name: 'Kiwa Umbrella'
    description: 'Unique masterpiece painted with different kinds of kiwa colors'
    price: 28.74
    quantity: 0
    image: paraplu.png
  -
    name: 'Kiwa cycling shirt'
    price: 14
    image: cyclingshirt.jpg	
  -
    name: 'Kiwa Rain Jacket'
    price: 17
    image: rainjacket.jpg	
  -
    name: 'Global OWASP WASPY Award 2017 Nomination'
    description: 'Your chance to nominate up to three quiet pillars of the OWASP community ends 2017-06-30! <a href="https://www.owasp.org/index.php/WASPY_Awards_2017">Nominate now!</a>'
    price: 0.03
    image: waspy.png
    deletedDate: '2017-07-01'
  -
    name: 'OWASP Juice Shop Sweden Tour 2017 Sticker Sheet (Special Edition)'
    description: '10 sheets of Sweden-themed stickers with 15 stickers on each.'
    price: 19.1
    image: undefined_kiwa.png
    deletedDate: '2017-09-20'
  -
    name: 'Rippertuer Special Juice'
    description: 'Contains a magical collection of the rarest fruits gathered from all around the world, like Cherymoya Annona cherimola, Jabuticaba Myrciaria cauliflora, Bael Aegle marmelos... and others, at an unbelievable price! <br/><span style="color:red;">This item has been made unavailable because of lack of safety standards.</span>'
    price: 16.99
    image: undefined.jpg
    keywordsForPastebinDataLeakChallenge:
      - hueteroneel
      - eurogium edule
  -
    name: 'Pwning OWASP Juice Shop'
    description: '<em>The official Companion Guide</em> by Björn Kimminich.'
    price: 5.99
    image: cover_small.jpg
    reviews:
      - { text: 'Even more interesting than watching Interdimensional Cable!', author: morty }
  -
    name: 'Kiwa Americano Mug'
    description: 'Might be removed lated because of a mugging.'
    price: 7.74
    quantity: 6
    image: americano.jpg
ctf:
  showFlagsInNotifications: false
  showCountryDetailsInNotifications: none # Options: none  name  flag  both
  countryMapping: ~
