name: "CI (Continuous Integration)"

on:
  # ENTENDER AS TRIGERS
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: "Check out Git repository"
        uses: actions/checkout@e2f20e631ae6d7dd3b768f56a5d2af784dd54791
        
      - name: "Use Node.js 16"
        uses: actions/setup-node@8c91899e586c5b171469028077307d293428b516
        with:
          node-version: 16

      - name: "Install application minimalistically"
        run: |
          npm install --ignore-scripts
          cd frontend
          npm install --ignore-scripts --legacy-peer-deps
      
      - name: "Lint source code"
        run: npm run lint

  test:
    runs-on: ubuntu-latest
    steps:
      - name: "Check out Git repository"
        uses: actions/checkout@e2f20e631ae6d7dd3b768f56a5d2af784dd54791
        
      - name: "Use Node.js 16"
        uses: actions/setup-node@8c91899e586c5b171469028077307d293428b516
        with:
          node-version: 16

      - name: "Install CLI tools"
        run: npm install -g @angular/cli@13
      
      - name: "Install application"
        run: npm install
      
      - name: "Execute unit tests"
        run: npm test

      - name: "Copy unit test coverage data"
        run: |
          cp build/reports/coverage/frontend-tests/lcov.info frontend-lcov.info
          cp build/reports/coverage/server-tests/lcov.info server-lcov.info

      - name: "Upload unit test coverage data"
        uses: actions/upload-artifact@6673cd052c4cd6fcf4b4e6e60ea986c889389535
        with:
          name: unit-test-lcov
          path: |
            frontend-lcov.info
            server-lcov.info

  api-test:
    runs-on: ubuntu-latest
    steps:
      - name: "Check out Git repository"
        uses: actions/checkout@e2f20e631ae6d7dd3b768f56a5d2af784dd54791
        
      - name: "Use Node.js 16"
        uses: actions/setup-node@8c91899e586c5b171469028077307d293428b516
        with:
          node-version: 16

      - name: "Install CLI tools"
        run: npm install -g @angular/cli@13
      
      - name: "Install application"
        run: npm install
      
      - name: "Execute integration tests"
        run: |
          export NODE_ENV=test
          npm run frisby

      - name: "Copy API test coverage data"
        run: cp build/reports/coverage/api-tests/lcov.info api-lcov.info

      - name: "Upload API test coverage data"
        uses: actions/upload-artifact@6673cd052c4cd6fcf4b4e6e60ea986c889389535
        with:
          name: api-test-lcov
          path: |
            api-lcov.info