name: "Continuous Integration (CI)"

on:
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: "Check out Git repository"
        uses: actions/checkout@e2f20e631ae6d7dd3b768f56a5d2af784dd54791

      - name: "Use Node.js 16"
        uses: actions/setup-node@8c91899e586c5b171469028077307d293428b516
        with:
          node-version: 16
          cache: 'npm'

      - name: Cache dependencies
        uses: actions/cache@9b0c1fce7a93df8e3bb8926b0d6e9d89e92f20a7
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-
      
      - name: "Install application minimalistically"
        run: |
          npm ci --ignore-scripts
      
      - name: "Lint source code"
        run: npm run lint

  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: "Check out Git repository"
        uses: actions/checkout@e2f20e631ae6d7dd3b768f56a5d2af784dd54791

      - name: "Use Node.js 16"
        uses: actions/setup-node@8c91899e586c5b171469028077307d293428b516
        with:
          node-version: 16
          cache: 'npm'

      - name: Cache dependencies
        uses: actions/cache@9b0c1fce7a93df8e3bb8926b0d6e9d89e92f20a7
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-
      
      - name: "Install application"
        run: npm ci --ignore-scripts
      
      - name: "Execute unit tests"
        run: npm run test:server

  semgrep:
    name: semgrep
    runs-on: ubuntu-latest
    env:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
    container:
      image: returntocorp/semgrep
    steps:
      - uses: actions/checkout@e2f20e631ae6d7dd3b768f56a5d2af784dd54791
      
      - run: semgrep ci
        continue-on-error: true

  snyk_code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@e2f20e631ae6d7dd3b768f56a5d2af784dd54791

      - uses: snyk/actions/setup@7fad562681122205233d1242c3bb39598c5393da

      - name: Snyk Code
        run: |
          npm install snyk-to-html --silent
          snyk code test --sarif-file-output=result_snyk_code.sarif
          snyk-to-html --input result_snyk_code.sarif --output result_snyk_code.html
          ls -lah
        continue-on-error: true

      - name: Upload Test results
        uses: actions/upload-artifact@83fd05a356d7e2593de66fc9913b3002723633cb
        with:
          name: Snyk Open Source report
          path: ${{github.workspace}}/result_snyk_code.html
    env:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

  snyk_open_source:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@e2f20e631ae6d7dd3b768f56a5d2af784dd54791

      - uses: snyk/actions/setup@7fad562681122205233d1242c3bb39598c5393da

      - name: Snyk Open Source
        run: |
          npm install snyk-to-html --silent
          snyk test --sarif-file-output=result_snyk_open_source.sarif
          snyk-to-html --input result_snyk_open_source.sarif --output result_snyk_open_source.html
        continue-on-error: true

      - name: Snyk Monitor
        run: snyk monitor

      - name: Upload Test results
        uses: actions/upload-artifact@83fd05a356d7e2593de66fc9913b3002723633cb
        with:
          name: Snyk Open Source report
          path: ${{github.workspace}}/result_snyk_open_source.html
    env:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}