name: "CI (Continuous Integration)"

on:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: "Check out Git repository"
        uses: actions/checkout@e2f20e631ae6d7dd3b768f56a5d2af784dd54791
        
      - name: "Use Node.js 16"
        uses: actions/setup-node@8c91899e586c5b171469028077307d293428b516
        with:
          node-version: 16
          cache: 'npm'

      - name: Cache dependencies
        uses: actions/cache@9b0c1fce7a93df8e3bb8926b0d6e9d89e92f20a7
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-

      - name: "Install application"
        run: npm ci --ignore-scripts
      
      - name: "Lint source code"
        run: npm run lint

  test:
    runs-on: ubuntu-latest
    steps:
      - name: "Check out Git repository"
        uses: actions/checkout@e2f20e631ae6d7dd3b768f56a5d2af784dd54791
        
      - name: "Use Node.js 16"
        uses: actions/setup-node@8c91899e586c5b171469028077307d293428b516
        with:
          node-version: 16
          cache: 'npm'

      - name: Cache dependencies
        uses: actions/cache@9b0c1fce7a93df8e3bb8926b0d6e9d89e92f20a7
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-
      
      - name: "Install application"
        run: npm ci --ignore-scripts
      
      - name: "Execute unit tests"
        run: npm run test:server

      - name: "Copy unit test coverage data"
        run: |
          cp build/reports/coverage/server-tests/lcov.info server-lcov.info

      - name: "Upload unit test coverage data"
        uses: actions/upload-artifact@6673cd052c4cd6fcf4b4e6e60ea986c889389535
        with:
          name: unit-test-lcov
          path: |
            server-lcov.info