name: Build Image and Test with Snyk

on:
  workflow_dispatch:
  workflow_call:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout Repo
          uses: actions/checkout@master

        - name: Set up QEMU
          uses: docker/setup-qemu-action@v3

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3

        - name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}

        - name: Build and push
          uses: docker/build-push-action@v5
          with:
            push: true
            tags: troysnyk/snyk-juice-shop:linux-action

        # - name: Test Built Image with Snyk
        #   uses: snyk/actions/docker@master
        #   env:
        #     SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        #   with:
        #     image: troysnyk/snyk-juice-shop
        #     args: --file=Dockerfile
