name: "ZAP Baseline Scan"

on:
  workflow_dispatch:

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan Juice Shop Instance
    steps:
      - name: OWASP ZAP Scan
        uses: zaproxy/action-baseline@7cea08522cd386f6c675776d5e4296aecf61f33b
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target: 'https://www.liveappsec.com'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a -j'
