name: "ZAP Baseline Scan"

on:
  schedule:
    - cron:  '0 18 * * 6'

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan Juice Shop preview instance on Heroku
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
        with:
          ref: develop
      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.3.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target: 'https://juice-shop-gh-ch.herokuapp.com'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a -j'
